version: '3.8'

services:
  web:
    image: php:8.2-apache
    container_name: php
    restart: always
    volumes:
      - ./public:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - PHP_EXTENSION=pdo_mysql
    command: >
      bash -c "docker-php-ext-install pdo pdo_mysql && apache2-foreground"


  db:
    image: mariadb:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: oficina
      MYSQL_USER: ezequiel
      MYSQL_PASSWORD: ezedbquiel
    volumes:
      - db_data:/var/lib/mysql
      - ./database/db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "3306:3306"

volumes:
  db_data:
